1.1 Creating NumPy Arrays

In [1]:
import numpy as np

lst = [1,2,3,4,5,6]

# Creating an aray from list
arr = np.array(lst)

arr

array([1, 2, 3, 4, 5, 6])

In [2]:
lst = [1,2,3,4,5,6]

# Creating an array of floats from list
arr = np.array(lst, dtype = float)
arr

array([1., 2., 3., 4., 5., 6.])

In [4]:
names = [["Jon","Mary","Paul"],["Peter","Ben","Saul"]]

arr1 = np.array(names)
arr1

array([['Jon', 'Mary', 'Paul'],
       ['Peter', 'Ben', 'Saul']], dtype='<U5')

In [5]:
# Checking for number of dimensions the arra
arr1.ndim

2

In [6]:
arr2 = np.arange(0,50,5)
arr2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [7]:
arr3 = np.zeros((2,3),dtype = float)
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr3 = np.ones((2,3), dtype = float)
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# Create a random number generator
rng = np.random.default_rng()

# Generate random integers from 0 to 9
rng.integers(low=0, high=10, size=(2,4))

array([[3, 7, 8, 1],
       [5, 3, 7, 7]])

In [12]:
# Create a random number generator
rng = np.random.default_rng(seed = 24)

# Generate random floats between 0 and 1
rng.random((2,4))

array([[0.33026884, 0.40517732, 0.57473782, 0.50639977],
       [0.56421251, 0.56968731, 0.87411653, 0.08643046]])

1.2 Accessing Array Elements

In [21]:
# Call previously defined "names"
arr1

# Indexing to display only Mary and Paul
select_mary_paul = arr1[0,1:]
select_mary_paul

# Fancy indexing
select_peter = np.array([1,0])
select_paul = np.array([0,2])

select_peter_paul = arr1[select_peter,select_paul]
select_peter_paul

array(['Peter', 'Paul'], dtype='<U5')

In [24]:
# Boolean Indexing
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Create a boolena mask based on the condition
filter_array = arr % 2 != 0

arr[filter_array]

array([1, 3, 5, 7, 9])

1.3 Array Manipulation

In [26]:
# Creating an array 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Flatten the array using reshape
np.reshape(arr,9)

# Calling names variable
arr1 = np.array(names)

# Reshaping array to a (3,2) shape
new_array = np.reshape(arr1,(3,2))
new_array

array([['Jon', 'Mary'],
       ['Paul', 'Peter'],
       ['Ben', 'Saul']], dtype='<U5')

In [30]:
arr1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr2 = np.array([[100,110,120],[130,140,150]])

arr3 = np.concatenate((arr1,arr2), axis = 0)
arr3

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120],
       [130, 140, 150]])

In [33]:
names = [["Jon","Mary","Paul"],["Peter","Ben","Saul"]]

# Creating array
arr1 = np.array(names)

# Using split to split array into two parts
split_one, split_two = np.split(arr1,2)

print(split_one)
print(split_two)

[['Jon' 'Mary' 'Paul']]
[['Peter' 'Ben' 'Saul']]


In [43]:
arr1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr2 = np.array([[100,110,120],[130,140,150]])

# Performing a dot operation
np.dot(arr1,arr2.transpose())

array([[ 6800,  8600],
       [16700, 21200],
       [26600, 33800]])

1.4 Mathematical Functions

In [46]:
arr1 = np.array([[1,2,4],[6,7,8]])
arr2 = np.array([[3,3,6],[4,5,7]])

# Adding two arrays
add = np.add(arr1,arr2)
print(add)

# Subracting two arrays
subtract = np.subtract(arr1,arr2)
print(subtract)

# Multiplying two arrys
multiply = np.multiply(arr1,arr2)
print(multiply)

# Dividing two arrys
divide = np.divide(arr1,arr2)
print(divide)

# Raising array to power 2
power = np.power(arr1,2)
print(power)

# Finding sqrt of array
sqrt = np.sqrt(arr2)
print(sqrt)

[[ 4  5 10]
 [10 12 15]]
[[-2 -1 -2]
 [ 2  2  1]]
[[ 3  6 24]
 [24 35 56]]
[[0.33333333 0.66666667 0.66666667]
 [1.5        1.4        1.14285714]]
[[ 1  4 16]
 [36 49 64]]
[[1.73205081 1.73205081 2.44948974]
 [2.         2.23606798 2.64575131]]


1.5 Statistical Functions

In [53]:
# Calling arr2 variable

# Calculate the mean of each row
mean = np.mean(arr2,axis=1)
mean

array([4.        , 5.33333333])

In [54]:
# Calculating the median of each row
median = np.median(arr2,axis=1)
print(median)

[3. 5.]


In [55]:
# Calculating the std of each column
std = np.std(arr2,axis=0)
print(std)

[0.5 1.  0.5]


In [57]:
# Calculating the var of each column
variance = np.var(arr2,axis=0)
print(variance)

[0.25 1.   0.25]


In [58]:
#Calculating the min of each column 
min = np.min(arr2,axis=0)
print(min)

[3 3 6]


In [59]:
# Calculating the max of the whole array
max = np.max(arr2,axis=None)
print(max)

7
